version: "3.8"

services:
  app:
    build: .
    container_name: HealthCare_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/healthCare?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_URL: redis://redis:6379
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_SSL : false
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET : your_secret_key_must_be_at_least_32_characters_long_for_HS256_algorithm!
      JWT_EXPIRATION : 36000000
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: healthCare
      MYSQL_ROOT_PASSWORD: "yourpassword"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network


networks:
  app_network:

volumes:
  db_data: